# Generated by Django 3.1.1 on 2020-09-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200912_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='MyCourse',
        ),
        migrations.AddField(
            model_name='quota',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course', to='students.Subject'),
        ),
    ]
