# Generated by Django 3.1.1 on 2020-09-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200912_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='name',
        ),
    ]
