# Generated by Django 3.1.1 on 2020-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200913_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
